apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "wp-prod-issuer"
spec:
  rules:
  - host: wordpress.linuxteknosia.net
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port: 
              number: 80
  tls:
  - hosts:
    - "*.linuxteknosia.net"
    secretName: wordpress-tls 
