apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wordpress
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: budi@busanid.dev
   privateKeySecretRef:
     name: letsencrypt-staging
   solvers:
   - http01:
      ingress:
        class: nginx
